# Generated by gallery/generate.py; do not hand-edit.
forceload add 204 204 244 240
fill 204 100 204 244 104 240 minecraft:air replace
fill 204 99 204 244 99 240 minecraft:smooth_stone replace
# 01 statue-ancient
setblock 208 100 208 cobblefurnies:statue_ancient[facing=south,half=lower] replace
setblock 208 101 208 cobblefurnies:statue_ancient[facing=south,half=upper] replace
# 02 statue-bulbasaur
setblock 212 100 208 cobblefurnies:statue_bulbasaur[facing=south,half=lower] replace
setblock 212 101 208 cobblefurnies:statue_bulbasaur[facing=south,half=upper] replace
# 03 statue-charmander
setblock 216 100 208 cobblefurnies:statue_charmander[facing=south,half=lower] replace
setblock 216 101 208 cobblefurnies:statue_charmander[facing=south,half=upper] replace
# 04 statue-pikachu
setblock 220 100 208 cobblefurnies:statue_pikachu[facing=south,half=lower] replace
setblock 220 101 208 cobblefurnies:statue_pikachu[facing=south,half=upper] replace
# 05 statue-squirtle
setblock 224 100 208 cobblefurnies:statue_squirtle[facing=south,half=lower] replace
setblock 224 101 208 cobblefurnies:statue_squirtle[facing=south,half=upper] replace
# 06 red-poke-wool
setblock 208 100 216 cobblefurnies:red_poke_wool replace
# 07 orange-poke-wool
setblock 210 100 216 cobblefurnies:orange_poke_wool replace
# 08 yellow-poke-wool
setblock 212 100 216 cobblefurnies:yellow_poke_wool replace
# 09 brown-poke-wool
setblock 214 100 216 cobblefurnies:brown_poke_wool replace
# 10 lime-poke-wool
setblock 216 100 216 cobblefurnies:lime_poke_wool replace
# 11 green-poke-wool
setblock 218 100 216 cobblefurnies:green_poke_wool replace
# 12 cyan-poke-wool
setblock 220 100 216 cobblefurnies:cyan_poke_wool replace
# 13 light_blue-poke-wool
setblock 222 100 216 cobblefurnies:light_blue_poke_wool replace
# 14 blue-poke-wool
setblock 208 100 218 cobblefurnies:blue_poke_wool replace
# 15 magenta-poke-wool
setblock 210 100 218 cobblefurnies:magenta_poke_wool replace
# 16 purple-poke-wool
setblock 212 100 218 cobblefurnies:purple_poke_wool replace
# 17 pink-poke-wool
setblock 214 100 218 cobblefurnies:pink_poke_wool replace
# 18 white-poke-wool
setblock 216 100 218 cobblefurnies:white_poke_wool replace
# 19 light_gray-poke-wool
setblock 218 100 218 cobblefurnies:light_gray_poke_wool replace
# 20 gray-poke-wool
setblock 220 100 218 cobblefurnies:gray_poke_wool replace
# 21 black-poke-wool
setblock 222 100 218 cobblefurnies:black_poke_wool replace
# 22 red-poke-wool-carpet
setblock 208 100 224 cobblefurnies:red_poke_wool_carpet replace
# 23 orange-poke-wool-carpet
setblock 210 100 224 cobblefurnies:orange_poke_wool_carpet replace
# 24 yellow-poke-wool-carpet
setblock 212 100 224 cobblefurnies:yellow_poke_wool_carpet replace
# 25 brown-poke-wool-carpet
setblock 214 100 224 cobblefurnies:brown_poke_wool_carpet replace
# 26 lime-poke-wool-carpet
setblock 216 100 224 cobblefurnies:lime_poke_wool_carpet replace
# 27 green-poke-wool-carpet
setblock 218 100 224 cobblefurnies:green_poke_wool_carpet replace
# 28 cyan-poke-wool-carpet
setblock 220 100 224 cobblefurnies:cyan_poke_wool_carpet replace
# 29 light_blue-poke-wool-carpet
setblock 222 100 224 cobblefurnies:light_blue_poke_wool_carpet replace
# 30 blue-poke-wool-carpet
setblock 208 100 226 cobblefurnies:blue_poke_wool_carpet replace
# 31 magenta-poke-wool-carpet
setblock 210 100 226 cobblefurnies:magenta_poke_wool_carpet replace
# 32 purple-poke-wool-carpet
setblock 212 100 226 cobblefurnies:purple_poke_wool_carpet replace
# 33 pink-poke-wool-carpet
setblock 214 100 226 cobblefurnies:pink_poke_wool_carpet replace
# 34 white-poke-wool-carpet
setblock 216 100 226 cobblefurnies:white_poke_wool_carpet replace
# 35 light_gray-poke-wool-carpet
setblock 218 100 226 cobblefurnies:light_gray_poke_wool_carpet replace
# 36 gray-poke-wool-carpet
setblock 220 100 226 cobblefurnies:gray_poke_wool_carpet replace
# 37 black-poke-wool-carpet
setblock 222 100 226 cobblefurnies:black_poke_wool_carpet replace
# 38 red-wool-open-l
setblock 232 100 216 cobblefurnies:red_poke_wool replace
setblock 233 100 216 cobblefurnies:red_poke_wool replace
setblock 232 100 215 cobblefurnies:red_poke_wool replace
# 39 red-wool-full-three-by-three
setblock 238 100 215 cobblefurnies:red_poke_wool replace
setblock 239 100 215 cobblefurnies:red_poke_wool replace
setblock 240 100 215 cobblefurnies:red_poke_wool replace
setblock 238 100 216 cobblefurnies:red_poke_wool replace
setblock 239 100 216 cobblefurnies:red_poke_wool replace
setblock 240 100 216 cobblefurnies:red_poke_wool replace
setblock 238 100 217 cobblefurnies:red_poke_wool replace
setblock 239 100 217 cobblefurnies:red_poke_wool replace
setblock 240 100 217 cobblefurnies:red_poke_wool replace
# 40 blue-carpet-open-l
setblock 232 100 226 cobblefurnies:blue_poke_wool_carpet replace
setblock 233 100 226 cobblefurnies:blue_poke_wool_carpet replace
setblock 232 100 225 cobblefurnies:blue_poke_wool_carpet replace
# 41 blue-carpet-full-three-by-three
setblock 238 100 225 cobblefurnies:blue_poke_wool_carpet replace
setblock 239 100 225 cobblefurnies:blue_poke_wool_carpet replace
setblock 240 100 225 cobblefurnies:blue_poke_wool_carpet replace
setblock 238 100 226 cobblefurnies:blue_poke_wool_carpet replace
setblock 239 100 226 cobblefurnies:blue_poke_wool_carpet replace
setblock 240 100 226 cobblefurnies:blue_poke_wool_carpet replace
setblock 238 100 227 cobblefurnies:blue_poke_wool_carpet replace
setblock 239 100 227 cobblefurnies:blue_poke_wool_carpet replace
setblock 240 100 227 cobblefurnies:blue_poke_wool_carpet replace
# 42 stock-oak-chair
setblock 208 100 236 cobblefurnies:oak_chair[facing=south,waterlogged=false] replace
# 43 stock-oak-table
setblock 212 100 236 cobblefurnies:oak_table[east=false,north=false,south=false,waterlogged=false,west=false] replace
# 44 stock-red-sofa
setblock 216 100 236 cobblefurnies:red_sofa[facing=south,type=single,waterlogged=false] replace
# 45 stock-red-cabinetry
setblock 220 100 236 cobblefurnies:red_cabinetry[facing=south,shape=default,waterlogged=false] replace
# 46 stock-poke-ball-desk
setblock 224 100 236 cobblefurnies:poke_ball_desk[facing=south] replace
tellraw @a [{"text":"Built CobbleFurnies 46-cell / 71-block gallery.","color":"green"}]
