# Generated by gallery/generate.py; do not hand-edit.
scoreboard objectives add cobblefurnies_gallery dummy
scoreboard players set #failures cobblefurnies_gallery 0
execute unless block 208 100 208 cobblefurnies:statue_ancient[facing=south,half=lower] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 208 101 208 cobblefurnies:statue_ancient[facing=south,half=upper] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless data block 208 100 208 {id:"cobblefurnies:statue"} run scoreboard players add #failures cobblefurnies_gallery 1
execute if data block 208 101 208 id run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 212 100 208 cobblefurnies:statue_bulbasaur[facing=south,half=lower] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 212 101 208 cobblefurnies:statue_bulbasaur[facing=south,half=upper] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless data block 212 100 208 {id:"cobblefurnies:statue"} run scoreboard players add #failures cobblefurnies_gallery 1
execute if data block 212 101 208 id run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 216 100 208 cobblefurnies:statue_charmander[facing=south,half=lower] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 216 101 208 cobblefurnies:statue_charmander[facing=south,half=upper] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless data block 216 100 208 {id:"cobblefurnies:statue"} run scoreboard players add #failures cobblefurnies_gallery 1
execute if data block 216 101 208 id run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 220 100 208 cobblefurnies:statue_pikachu[facing=south,half=lower] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 220 101 208 cobblefurnies:statue_pikachu[facing=south,half=upper] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless data block 220 100 208 {id:"cobblefurnies:statue"} run scoreboard players add #failures cobblefurnies_gallery 1
execute if data block 220 101 208 id run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 224 100 208 cobblefurnies:statue_squirtle[facing=south,half=lower] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 224 101 208 cobblefurnies:statue_squirtle[facing=south,half=upper] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless data block 224 100 208 {id:"cobblefurnies:statue"} run scoreboard players add #failures cobblefurnies_gallery 1
execute if data block 224 101 208 id run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 208 100 216 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 210 100 216 cobblefurnies:orange_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 212 100 216 cobblefurnies:yellow_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 214 100 216 cobblefurnies:brown_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 216 100 216 cobblefurnies:lime_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 218 100 216 cobblefurnies:green_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 220 100 216 cobblefurnies:cyan_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 222 100 216 cobblefurnies:light_blue_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 208 100 218 cobblefurnies:blue_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 210 100 218 cobblefurnies:magenta_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 212 100 218 cobblefurnies:purple_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 214 100 218 cobblefurnies:pink_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 216 100 218 cobblefurnies:white_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 218 100 218 cobblefurnies:light_gray_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 220 100 218 cobblefurnies:gray_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 222 100 218 cobblefurnies:black_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 208 100 224 cobblefurnies:red_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 210 100 224 cobblefurnies:orange_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 212 100 224 cobblefurnies:yellow_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 214 100 224 cobblefurnies:brown_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 216 100 224 cobblefurnies:lime_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 218 100 224 cobblefurnies:green_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 220 100 224 cobblefurnies:cyan_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 222 100 224 cobblefurnies:light_blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 208 100 226 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 210 100 226 cobblefurnies:magenta_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 212 100 226 cobblefurnies:purple_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 214 100 226 cobblefurnies:pink_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 216 100 226 cobblefurnies:white_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 218 100 226 cobblefurnies:light_gray_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 220 100 226 cobblefurnies:gray_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 222 100 226 cobblefurnies:black_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 232 100 216 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 233 100 216 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 232 100 215 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 238 100 215 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 239 100 215 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 240 100 215 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 238 100 216 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 239 100 216 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 240 100 216 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 238 100 217 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 239 100 217 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 240 100 217 cobblefurnies:red_poke_wool run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 232 100 226 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 233 100 226 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 232 100 225 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 238 100 225 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 239 100 225 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 240 100 225 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 238 100 226 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 239 100 226 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 240 100 226 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 238 100 227 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 239 100 227 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 240 100 227 cobblefurnies:blue_poke_wool_carpet run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 208 100 236 cobblefurnies:oak_chair[facing=south,waterlogged=false] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 212 100 236 cobblefurnies:oak_table[east=false,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 216 100 236 cobblefurnies:red_sofa[facing=south,type=single,waterlogged=false] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 220 100 236 cobblefurnies:red_cabinetry[facing=south,shape=default,waterlogged=false] run scoreboard players add #failures cobblefurnies_gallery 1
execute unless block 224 100 236 cobblefurnies:poke_ball_desk[facing=south] run scoreboard players add #failures cobblefurnies_gallery 1
execute if score #failures cobblefurnies_gallery matches 0 run tellraw @a [{"text":"CobbleFurnies gallery verification passed: 46 cells / 71 blocks.","color":"green"}]
execute unless score #failures cobblefurnies_gallery matches 0 run tellraw @a [{"text":"CobbleFurnies gallery verification failed; inspect #failures.","color":"red"}]
